---

- name: add blockedomain settings for mdl
  template:
    src: blockeddomain.hosts.j2
    dest: "{{ bind_etc }}/blockeddomain.hosts"
    mode: 0644

- name: add malware domains list zone in local configuration
  blockinfile:
    dest: "{{ bind_etc }}/named.conf.local"
    marker: '// {mark} ANSIBLE MANAGED BLOCK: malware domains list'
    block: |
       include "{{ bind_etc }}/spywaredomains.zones";
  notify:
    - restart bind

- name: install update script
  template:
    src: bind-mdl-update.sh.j2
    dest: /usr/local/bin/bind-mdl-update.sh
    mode: 0755

- name: recover first list
  command: "/usr/local/bin/bind-mdl-update.sh creates={{ bind_etc }}/spywaredomains.zones"
  notify:
    - restart bind

