---

- name: apt | Install bind9
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - bind9
    - dnsutils
    - dnssec-tools
    - libnet-dns-sec-perl
    - libmailtools-perl
    - libcrypt-openssl-random-perl
    - ldnsutils
    - wget
    - unzip
    - resolvconf

- include: resolvconf.yml

